name: musalbas
markdown: redcarpet
pygments: true
about: Personal homepage of Mustafa Al-Bassam
host: 127.0.0.1
port: 9083
urls:
    - text: Email
      url: mailto:mus@musalbas.com
    - text: Twitter
      url: https://twitter.com/musalbas
    - text: GitHub
      url: https://github.com/musalbas
