# Site settings
title: Mustafa Al-Bassam's blog
email: mus@musalbas.com
description: The personal blog of Mustafa Al-Bassam.
baseurl: "/blog"
url: "https://musalbas.com"
twitter_username: musalbas
github_username: musalbas

# Build settings
markdown: kramdown
